# Generated by Django 3.1.7 on 2021-05-16 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
