# Generated by Django 3.1.7 on 2021-05-27 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_education_experience_keyskill'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='user',
        ),
        migrations.AddField(
            model_name='education',
            name='user',
            field=models.ManyToManyField(to='myapp.Profile'),
        ),
        migrations.RemoveField(
            model_name='experience',
            name='user',
        ),
        migrations.AddField(
            model_name='experience',
            name='user',
            field=models.ManyToManyField(to='myapp.Profile'),
        ),
        migrations.RemoveField(
            model_name='keyskill',
            name='user',
        ),
        migrations.AddField(
            model_name='keyskill',
            name='user',
            field=models.ManyToManyField(to='myapp.Profile'),
        ),
    ]
