# Generated by Django 3.1.7 on 2021-05-31 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_auto_20210528_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='name',
        ),
        migrations.AddField(
            model_name='education',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='school_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='description',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='experience',
            name='job_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='myapp.profile'),
        ),
        migrations.AlterField(
            model_name='keyskill',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='myapp.profile'),
        ),
    ]
